use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHDownloader_Example' do
  pod 'AHDownloader', :path => '../'

  target 'AHDownloader_Tests' do
    inherit! :search_paths

    
  end
end
